controller:
  motion_law_parameters:
    max_velocity: [2, 2, 15]
    max_acceleration: [3, 2, 200]

  cascade_controllers:
  - name: "joint1"
    inner:
      Kp: 68.0
      Ki: 137.0
      Kd: 0.0
      filters_on_derivative_error:
        - type: NotchFilter
          natural_frequency: 540
          zeros_damping: 0.2
          poles_damping: 0.8
    outer:
      Kp: 26.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 75.0
      Ki: 264.0
      Kd: 0.0
      filters_on_derivative_error:
        - type: NotchFilter
          natural_frequency: 630
          zeros_damping: 0.2
          poles_damping: 0.9
    outer:
      Kp: 20.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint3"
    inner:
      Kp: 44.0
      Ki: 170.0
      Kd: 0.0
      filters_on_derivative_error:
        - type: NotchFilter
          natural_frequency: 608
          zeros_damping: 0.2
          poles_damping: 0.9
    outer:
      Kp: 20.0
      Ki: 0.0
      Kd: 0.0

model_parameters:
  - -0.033691
  - 0.000000
  - -0.000000
  - 0.000000
  - -0.000000
  - -0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - -1.167545
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 1.157463
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.000000
  - 0.416787
  - 3.402295
  - 1.342004
  - -0.094726
  - -0.411541
  - -0.285911




